import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import {
  ConnectWallet,
  useAddress,
  useContract,
  useContractWrite,
} from "@thirdweb-dev/react";
import {
  TWAccountFactoryAddress,
  activeChain,
  paperClientId,
} from "@/const/contracts";
import { Button } from "@chakra-ui/react";
import { SmartWallet } from "@thirdweb-dev/wallets/evm/wallets/smart-wallet";
import { PaperWallet } from "@thirdweb-dev/wallets";
import { ThirdwebSDK } from "@thirdweb-dev/sdk";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { contract: factoryContract, isLoading: isFactoryContractLoading } =
    useContract(TWAccountFactoryAddress, "custom");
  const address = useAddress();

  const createSmartWallet = async () => {
    const newWallet = new SmartWallet({
      factoryAddress: TWAccountFactoryAddress,
      chain: activeChain,
      thirdwebApiKey: "",
      gasless: true,
    });

    const personalWallet = new PaperWallet({
      clientId: paperClientId,
      chain: activeChain,
      chains: [activeChain],
    });
    await personalWallet.connect();

    const personalAddress = await personalWallet.getAddress();

    await newWallet.connect({
      accountId: personalAddress,
      personalWallet: personalWallet,
    });
    console.log(newWallet);

    const newWalletAddress = await newWallet.getAddress();

    console.log(newWalletAddress);

    const sdk = ThirdwebSDK.fromWallet(newWallet, activeChain);
    const contract = (await sdk).getContract(
      "0x8D9919db3CD6aF84e8A12CedC3c5A694Bf026aB8",
      "edition-drop"
    );
    const claim = (await contract).claim(0, 1);
    console.log(claim);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button onClick={createSmartWallet}>Create Smart Wallet</Button>
    </>
  );
}
